name: tsat_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png